# Generated by Django 3.2.7 on 2021-09-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210917_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='theBank/media/users/default.jpeg', upload_to='theBank/media/users/profile pictures/', verbose_name='Profile picture'),
        ),
    ]
