# Generated by Django 3.2.7 on 2021-09-24 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propetyMarket', '0014_auto_20210924_1916'),
        ('users', '0004_client_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propetyMarket.developer', verbose_name='Agency the agent belongs to')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='the user name')),
            ],
        ),
    ]
