# Generated by Django 4.0.6 on 2022-07-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propetyMarket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('villa', 'villa'), ('retail', 'retail'), ('serviced apartment', 'serviced apartment'), ('restaurant', 'restaurant'), ('town house', 'town house'), ('pent house', 'pent house'), ('clinic', 'clinic'), ('studio', 'studio'), ('Industrial', 'Industrial'), ('chalet', 'chalet'), ('office', 'office'), ('apartment', 'apartment'), ('duplex', 'duplex'), ('twin house', 'twin house')], max_length=100, verbose_name='Property Type'),
        ),
    ]
