# Generated by Django 3.2.5 on 2021-09-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propetyMarket', '0002_agent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('studio', 'studio'), ('apartment', 'apartment'), ('Industrial', 'Industrial'), ('town house', 'town house'), ('clinic', 'clinic'), ('duplex', 'duplex'), ('retail', 'retail'), ('office', 'office'), ('chalet', 'chalet'), ('restaurant', 'restaurant'), ('villa', 'villa'), ('twin house', 'twin house'), ('pent house', 'pent house'), ('serviced apartment', 'serviced apartment')], max_length=100, verbose_name='Property Type'),
        ),
    ]
