# Generated by Django 3.2.5 on 2021-09-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propetyMarket', '0003_alter_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.BooleanField(choices=[(False, 'For rent'), (True, 'For sale')], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('restaurant', 'restaurant'), ('Industrial', 'Industrial'), ('apartment', 'apartment'), ('retail', 'retail'), ('twin house', 'twin house'), ('chalet', 'chalet'), ('office', 'office'), ('pent house', 'pent house'), ('villa', 'villa'), ('duplex', 'duplex'), ('clinic', 'clinic'), ('studio', 'studio'), ('serviced apartment', 'serviced apartment'), ('town house', 'town house')], max_length=100, verbose_name='Property Type'),
        ),
    ]
