# Generated by Django 3.2.5 on 2021-09-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propetyMarket', '0005_alter_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.BooleanField(choices=[(True, 'For sale'), (False, 'For rent')], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('chalet', 'chalet'), ('duplex', 'duplex'), ('villa', 'villa'), ('office', 'office'), ('pent house', 'pent house'), ('retail', 'retail'), ('town house', 'town house'), ('apartment', 'apartment'), ('restaurant', 'restaurant'), ('studio', 'studio'), ('twin house', 'twin house'), ('Industrial', 'Industrial'), ('clinic', 'clinic'), ('serviced apartment', 'serviced apartment')], max_length=100, verbose_name='Property Type'),
        ),
    ]
