# Generated by Django 3.2.5 on 2021-09-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propetyMarket', '0006_auto_20210917_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('villa', 'villa'), ('duplex', 'duplex'), ('studio', 'studio'), ('retail', 'retail'), ('restaurant', 'restaurant'), ('office', 'office'), ('serviced apartment', 'serviced apartment'), ('twin house', 'twin house'), ('apartment', 'apartment'), ('chalet', 'chalet'), ('pent house', 'pent house'), ('town house', 'town house'), ('clinic', 'clinic'), ('Industrial', 'Industrial')], max_length=100, verbose_name='Property Type'),
        ),
    ]
