# Generated by Django 3.2.5 on 2021-09-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propetyMarket', '0007_alter_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.BooleanField(choices=[(False, 'For rent'), (True, 'For sale')], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('serviced apartment', 'serviced apartment'), ('apartment', 'apartment'), ('studio', 'studio'), ('villa', 'villa'), ('duplex', 'duplex'), ('pent house', 'pent house'), ('retail', 'retail'), ('town house', 'town house'), ('chalet', 'chalet'), ('office', 'office'), ('clinic', 'clinic'), ('restaurant', 'restaurant'), ('Industrial', 'Industrial'), ('twin house', 'twin house')], max_length=100, verbose_name='Property Type'),
        ),
    ]
