# Generated by Django 3.2.5 on 2021-09-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propetyMarket', '0008_auto_20210918_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('chalet', 'chalet'), ('Industrial', 'Industrial'), ('studio', 'studio'), ('town house', 'town house'), ('serviced apartment', 'serviced apartment'), ('duplex', 'duplex'), ('pent house', 'pent house'), ('retail', 'retail'), ('twin house', 'twin house'), ('apartment', 'apartment'), ('office', 'office'), ('restaurant', 'restaurant'), ('villa', 'villa'), ('clinic', 'clinic')], max_length=100, verbose_name='Property Type'),
        ),
    ]
