# Generated by Django 3.2.7 on 2021-09-24 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propetyMarket', '0009_alter_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.BooleanField(choices=[(True, 'For sale'), (False, 'For rent')], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('Industrial', 'Industrial'), ('twin house', 'twin house'), ('clinic', 'clinic'), ('serviced apartment', 'serviced apartment'), ('chalet', 'chalet'), ('office', 'office'), ('retail', 'retail'), ('duplex', 'duplex'), ('villa', 'villa'), ('pent house', 'pent house'), ('apartment', 'apartment'), ('restaurant', 'restaurant'), ('studio', 'studio'), ('town house', 'town house')], max_length=100, verbose_name='Property Type'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorites', models.ManyToManyField(blank=True, null=True, to='propetyMarket.Property', verbose_name='Favorites')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='the user object')),
            ],
        ),
    ]
