# Generated by Django 3.2.7 on 2021-09-24 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propetyMarket', '0010_auto_20210924_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='favorites',
        ),
        migrations.AddField(
            model_name='client',
            name='favorites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propetyMarket.property', verbose_name='Favorites'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.BooleanField(choices=[(False, 'For rent'), (True, 'For sale')], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('Industrial', 'Industrial'), ('restaurant', 'restaurant'), ('pent house', 'pent house'), ('apartment', 'apartment'), ('office', 'office'), ('villa', 'villa'), ('chalet', 'chalet'), ('town house', 'town house'), ('twin house', 'twin house'), ('retail', 'retail'), ('studio', 'studio'), ('duplex', 'duplex'), ('serviced apartment', 'serviced apartment'), ('clinic', 'clinic')], max_length=100, verbose_name='Property Type'),
        ),
    ]
