# Generated by Django 3.2.7 on 2021-09-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propetyMarket', '0011_auto_20210924_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='favorites',
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.BooleanField(choices=[(True, 'For sale'), (False, 'For rent')], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('apartment', 'apartment'), ('chalet', 'chalet'), ('town house', 'town house'), ('restaurant', 'restaurant'), ('retail', 'retail'), ('office', 'office'), ('Industrial', 'Industrial'), ('pent house', 'pent house'), ('twin house', 'twin house'), ('studio', 'studio'), ('villa', 'villa'), ('duplex', 'duplex'), ('serviced apartment', 'serviced apartment'), ('clinic', 'clinic')], max_length=100, verbose_name='Property Type'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propetyMarket.client', verbose_name='Client it belongs to')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propetyMarket.property', verbose_name='Property selected')),
            ],
        ),
    ]
