# Generated by Django 3.2.7 on 2021-09-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propetyMarket', '0012_auto_20210924_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='client',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='property',
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.BooleanField(choices=[(False, 'For rent'), (True, 'For sale')], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('Industrial', 'Industrial'), ('pent house', 'pent house'), ('villa', 'villa'), ('duplex', 'duplex'), ('retail', 'retail'), ('twin house', 'twin house'), ('town house', 'town house'), ('serviced apartment', 'serviced apartment'), ('chalet', 'chalet'), ('restaurant', 'restaurant'), ('studio', 'studio'), ('clinic', 'clinic'), ('apartment', 'apartment'), ('office', 'office')], max_length=100, verbose_name='Property Type'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
