# Generated by Django 3.2.7 on 2021-09-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propetyMarket', '0013_auto_20210924_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('Industrial', 'Industrial'), ('restaurant', 'restaurant'), ('pent house', 'pent house'), ('villa', 'villa'), ('serviced apartment', 'serviced apartment'), ('apartment', 'apartment'), ('retail', 'retail'), ('twin house', 'twin house'), ('clinic', 'clinic'), ('office', 'office'), ('studio', 'studio'), ('chalet', 'chalet'), ('town house', 'town house'), ('duplex', 'duplex')], max_length=100, verbose_name='Property Type'),
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
