# Generated by Django 3.2.5 on 2021-07-23 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Bank name')),
                ('office', models.CharField(max_length=100, verbose_name='Office address')),
                ('number', models.CharField(max_length=20, verbose_name='Number')),
                ('hotline', models.CharField(blank=True, max_length=10, null=True, verbose_name='Hotline')),
                ('email', models.EmailField(max_length=254, verbose_name='Bank email')),
                ('website', models.URLField(verbose_name='Website link')),
                ('image', models.ImageField(upload_to='GoldMark/images/banks/profiles/', verbose_name='Bank image')),
                ('interest', models.FloatField(verbose_name='Bank interest rate')),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Agency name')),
                ('email', models.EmailField(max_length=254, verbose_name='Agency email')),
                ('headquarters', models.CharField(max_length=100, verbose_name='Agency head quarters')),
                ('phone', models.CharField(max_length=20, verbose_name='Agency phone number')),
                ('image', models.ImageField(blank=True, null=True, upload_to='GoldMark/images/Agencies/profiles/', verbose_name='Agency logo')),
                ('website', models.URLField(verbose_name='Developer website')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Location name')),
                ('latitude', models.IntegerField(default=0, verbose_name='latitude coordinates')),
                ('longitude', models.IntegerField(default=0, verbose_name='longitude coordinates')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Property name')),
                ('status', models.BooleanField(choices=[(False, 'For rent'), (True, 'For sale')], verbose_name='Status')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('price', models.IntegerField(verbose_name='property price')),
                ('features', models.JSONField(blank=True, default=dict, null=True, verbose_name='property features')),
                ('info', models.JSONField(blank=True, default=dict, null=True, verbose_name='additional info as json string')),
                ('address', models.CharField(max_length=100, verbose_name='property address')),
                ('latitude', models.FloatField(default=0, verbose_name='google latitude')),
                ('longitude', models.FloatField(default=0, verbose_name='google longitude')),
                ('video', models.FileField(blank=True, null=True, upload_to='GoldMark/images/properties/videos/', verbose_name='property video')),
                ('time_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time posted')),
                ('size', models.IntegerField(verbose_name='property lot size')),
                ('description', models.CharField(max_length=500, verbose_name='property description')),
                ('plan', models.ImageField(blank=True, null=True, upload_to='GoldMark/images/properties/plans/', verbose_name='property plan view')),
                ('area', models.IntegerField(verbose_name='Property total area')),
                ('bedrooms', models.IntegerField(blank=True, null=True, verbose_name='Number of bedrooms')),
                ('bathrooms', models.IntegerField(blank=True, null=True, verbose_name='Number of bathrooms')),
                ('image', models.ImageField(upload_to='GoldMark/images/properties/residential/profiles', verbose_name='profile image')),
                ('garage', models.IntegerField(blank=True, null=True, verbose_name='number of garage places')),
                ('type', models.CharField(choices=[('office', 'office'), ('apartment', 'apartment'), ('duplex', 'duplex'), ('restaurant', 'restaurant'), ('town house', 'town house'), ('retail', 'retail'), ('pent house', 'pent house'), ('serviced apartment', 'serviced apartment'), ('villa', 'villa'), ('studio', 'studio'), ('Industrial', 'Industrial'), ('clinic', 'clinic'), ('chalet', 'chalet'), ('twin house', 'twin house')], max_length=100, verbose_name='Property Type')),
                ('Developer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GoldMark.developer', verbose_name='Development group')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GoldMark.location', verbose_name='Location')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GoldMark.property', verbose_name='Property it belongs to')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='GoldMark/images/properties/residential/', verbose_name='Image location')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GoldMark.property', verbose_name='Property it belongs to')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GoldMark.developer', verbose_name='Agency the agent belongs to')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='the user name')),
            ],
        ),
    ]
