# Generated by Django 3.2.5 on 2021-07-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoldMark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('office', 'office'), ('pent house', 'pent house'), ('retail', 'retail'), ('serviced apartment', 'serviced apartment'), ('Industrial', 'Industrial'), ('town house', 'town house'), ('studio', 'studio'), ('clinic', 'clinic'), ('chalet', 'chalet'), ('restaurant', 'restaurant'), ('twin house', 'twin house'), ('villa', 'villa'), ('duplex', 'duplex'), ('apartment', 'apartment')], max_length=100, verbose_name='Property Type'),
        ),
    ]
