# Generated by Django 3.2.5 on 2021-07-24 20:45

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('GoldMark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1000, 1000], upload_to='GoldMark/images/Agencies/profiles/', verbose_name='Agency logo'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[1000, 1000], upload_to='GoldMark/images/properties/residential/profiles', verbose_name='profile image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='plan',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[1000, 1000], upload_to='GoldMark/images/properties/plans/', verbose_name='property plan view'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('retail', 'retail'), ('apartment', 'apartment'), ('serviced apartment', 'serviced apartment'), ('town house', 'town house'), ('duplex', 'duplex'), ('studio', 'studio'), ('restaurant', 'restaurant'), ('villa', 'villa'), ('office', 'office'), ('twin house', 'twin house'), ('clinic', 'clinic'), ('pent house', 'pent house'), ('chalet', 'chalet'), ('Industrial', 'Industrial')], max_length=100, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[1000, 1000], upload_to='GoldMark/images/properties/residential/', verbose_name='Image location'),
        ),
    ]
