# Generated by Django 3.2.5 on 2021-07-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoldMark', '0002_alter_agency_headquarters'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='name',
            field=models.CharField(default='Emmaar Misr', max_length=20, verbose_name='Agency name'),
            preserve_default=False,
        ),
    ]
