# Generated by Django 3.2.5 on 2021-07-24 20:46

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('GoldMark', '0002_auto_20210724_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[250, 250], upload_to='GoldMark/images/Agencies/profiles/', verbose_name='Agency logo'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[250, 250], upload_to='GoldMark/images/properties/residential/profiles', verbose_name='profile image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='plan',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[250, 250], upload_to='GoldMark/images/properties/plans/', verbose_name='property plan view'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.BooleanField(choices=[(True, 'For sale'), (False, 'For rent')], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('clinic', 'clinic'), ('apartment', 'apartment'), ('duplex', 'duplex'), ('villa', 'villa'), ('studio', 'studio'), ('retail', 'retail'), ('chalet', 'chalet'), ('office', 'office'), ('twin house', 'twin house'), ('Industrial', 'Industrial'), ('town house', 'town house'), ('serviced apartment', 'serviced apartment'), ('restaurant', 'restaurant'), ('pent house', 'pent house')], max_length=100, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[100, 100], upload_to='GoldMark/images/properties/residential/', verbose_name='Image location'),
        ),
    ]
