# Generated by Django 3.2.5 on 2021-07-25 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GoldMark', '0002_alter_property_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category name')),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.BooleanField(choices=[(True, 'For sale'), (False, 'For rent')], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('restaurant', 'restaurant'), ('pent house', 'pent house'), ('clinic', 'clinic'), ('office', 'office'), ('town house', 'town house'), ('duplex', 'duplex'), ('serviced apartment', 'serviced apartment'), ('villa', 'villa'), ('retail', 'retail'), ('chalet', 'chalet'), ('apartment', 'apartment'), ('twin house', 'twin house'), ('studio', 'studio'), ('Industrial', 'Industrial')], max_length=100, verbose_name='Property Type'),
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoldMark.faqcategory', verbose_name='Category')),
            ],
        ),
    ]
