# Generated by Django 3.2.5 on 2021-07-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoldMark', '0003_auto_20210724_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='GoldMark/images/Agencies/profiles/', verbose_name='Agency logo'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(upload_to='GoldMark/images/properties/residential/profiles', verbose_name='profile image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='plan',
            field=models.ImageField(blank=True, null=True, upload_to='GoldMark/images/properties/plans/', verbose_name='property plan view'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.BooleanField(choices=[(False, 'For rent'), (True, 'For sale')], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('duplex', 'duplex'), ('restaurant', 'restaurant'), ('serviced apartment', 'serviced apartment'), ('office', 'office'), ('retail', 'retail'), ('chalet', 'chalet'), ('town house', 'town house'), ('pent house', 'pent house'), ('apartment', 'apartment'), ('studio', 'studio'), ('clinic', 'clinic'), ('villa', 'villa'), ('Industrial', 'Industrial'), ('twin house', 'twin house')], max_length=100, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='GoldMark/images/properties/residential/', verbose_name='Image location'),
        ),
    ]
