# Generated by Django 3.2.5 on 2021-07-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoldMark', '0004_alter_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.BooleanField(choices=[(False, 'For rent'), (True, 'For sale')], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('chalet', 'chalet'), ('town house', 'town house'), ('twin house', 'twin house'), ('restaurant', 'restaurant'), ('serviced apartment', 'serviced apartment'), ('pent house', 'pent house'), ('office', 'office'), ('retail', 'retail'), ('studio', 'studio'), ('apartment', 'apartment'), ('Industrial', 'Industrial'), ('clinic', 'clinic'), ('villa', 'villa'), ('duplex', 'duplex')], max_length=100, verbose_name='Property Type'),
        ),
    ]
