# Generated by Django 3.2.5 on 2021-07-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoldMark', '0005_auto_20210726_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('clinic', 'clinic'), ('villa', 'villa'), ('studio', 'studio'), ('office', 'office'), ('town house', 'town house'), ('chalet', 'chalet'), ('retail', 'retail'), ('twin house', 'twin house'), ('Industrial', 'Industrial'), ('duplex', 'duplex'), ('pent house', 'pent house'), ('serviced apartment', 'serviced apartment'), ('apartment', 'apartment'), ('restaurant', 'restaurant')], max_length=100, verbose_name='Property Type'),
        ),
    ]
