# Generated by Django 3.2.5 on 2021-07-27 19:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GoldMark', '0005_auto_20210726_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category name')),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='GoldMark.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.BooleanField(choices=[(True, 'For sale'), (False, 'For rent')], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('retail', 'retail'), ('restaurant', 'restaurant'), ('apartment', 'apartment'), ('villa', 'villa'), ('town house', 'town house'), ('twin house', 'twin house'), ('clinic', 'clinic'), ('chalet', 'chalet'), ('pent house', 'pent house'), ('Industrial', 'Industrial'), ('office', 'office'), ('duplex', 'duplex'), ('studio', 'studio'), ('serviced apartment', 'serviced apartment')], max_length=100, verbose_name='Property Type'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Blog name')),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2021, 7, 27, 19, 40, 1, 325363, tzinfo=utc), verbose_name='Date of posting')),
                ('image', models.ImageField(upload_to='GoldMark/images/Blog/main/', verbose_name='Blog image')),
                ('content', models.TextField(verbose_name=b'Blog content')),
                ('description', models.TextField(verbose_name='Blog description')),
                ('author', models.CharField(max_length=100, verbose_name='blog author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoldMark.blogcategory', verbose_name='Category name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='blog author')),
            ],
            options={
                'ordering': ['date_posted'],
            },
        ),
    ]
