# Generated by Django 3.2.5 on 2021-07-21 17:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GoldMark', '0006_auto_20210721_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Property name')),
                ('status', models.BooleanField(verbose_name='For sale')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('price', models.IntegerField(verbose_name='property price')),
                ('features', models.JSONField(default=dict, verbose_name='property features')),
                ('info', models.JSONField(default=dict, verbose_name='additional info as json string')),
                ('address', models.CharField(max_length=100, verbose_name='property address')),
                ('latitude', models.IntegerField(default=0, verbose_name='google latitude')),
                ('longitude', models.IntegerField(default=0, verbose_name='google longitude')),
                ('video', models.FileField(blank=True, null=True, upload_to='GoldMark/images/properties/videos/', verbose_name='property video')),
                ('time_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time posted')),
                ('size', models.IntegerField(verbose_name='property lot size')),
                ('description', models.CharField(max_length=500, verbose_name='property description')),
                ('plan', models.ImageField(blank=True, null=True, upload_to='GoldMark/images/properties/plans/', verbose_name='property plan view')),
                ('area', models.IntegerField(verbose_name='Property total area')),
                ('bedrooms', models.IntegerField(blank=True, null=True, verbose_name='Number of bedrooms')),
                ('bathrooms', models.IntegerField(blank=True, null=True, verbose_name='Number of bathrooms')),
                ('garage', models.IntegerField(blank=True, null=True, verbose_name='number of garage places')),
                ('type', models.CharField(choices=[('clinic', 'clinic'), ('town house', 'town house'), ('chalet', 'chalet'), ('retail', 'retail'), ('office', 'office'), ('villa', 'villa'), ('serviced apartment', 'serviced apartment'), ('apartment', 'apartment'), ('pent house', 'pent house'), ('twin house', 'twin house'), ('studio', 'studio'), ('restaurant', 'restaurant'), ('Industrial', 'Industrial'), ('duplex', 'duplex')], max_length=100, verbose_name='Property Type')),
                ('Agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GoldMark.agent', verbose_name='Agency')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GoldMark.location', verbose_name='Location')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GoldMark.property', verbose_name='Property it belongs to')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='GoldMark/images/properties/residential/', verbose_name='Image location')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GoldMark.property', verbose_name='Property it belongs to')),
            ],
        ),
        migrations.RemoveField(
            model_name='commercialpropertyimage',
            name='property',
        ),
        migrations.RemoveField(
            model_name='compoundproperty',
            name='Agent',
        ),
        migrations.RemoveField(
            model_name='compoundproperty',
            name='location',
        ),
        migrations.RemoveField(
            model_name='compoundpropertyimage',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='compoundpropertyimage',
            name='property',
        ),
        migrations.RemoveField(
            model_name='residentialproperty',
            name='Agent',
        ),
        migrations.RemoveField(
            model_name='residentialproperty',
            name='CompoundProperty',
        ),
        migrations.RemoveField(
            model_name='residentialproperty',
            name='location',
        ),
        migrations.RemoveField(
            model_name='residentialpropertyimage',
            name='property',
        ),
        migrations.DeleteModel(
            name='CommercialProperty',
        ),
        migrations.DeleteModel(
            name='CommercialPropertyImage',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompoundProperty',
        ),
        migrations.DeleteModel(
            name='CompoundPropertyImage',
        ),
        migrations.DeleteModel(
            name='ResidentialProperty',
        ),
        migrations.DeleteModel(
            name='ResidentialPropertyImage',
        ),
    ]
