# Generated by Django 3.2.5 on 2021-07-27 19:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('GoldMark', '0006_auto_20210727_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 19, 42, 26, 769890, tzinfo=utc), verbose_name='Date of posting'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.BooleanField(choices=[(False, 'For rent'), (True, 'For sale')], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('apartment', 'apartment'), ('villa', 'villa'), ('twin house', 'twin house'), ('retail', 'retail'), ('Industrial', 'Industrial'), ('clinic', 'clinic'), ('duplex', 'duplex'), ('office', 'office'), ('serviced apartment', 'serviced apartment'), ('restaurant', 'restaurant'), ('chalet', 'chalet'), ('town house', 'town house'), ('pent house', 'pent house'), ('studio', 'studio')], max_length=100, verbose_name='Property Type'),
        ),
    ]
