# Generated by Django 3.2.5 on 2021-07-27 19:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('GoldMark', '0007_auto_20210727_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='owner',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 27, 19, 42, 37, 826152, tzinfo=utc), verbose_name='Date of posting'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.BooleanField(choices=[(True, 'For sale'), (False, 'For rent')], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('restaurant', 'restaurant'), ('twin house', 'twin house'), ('town house', 'town house'), ('studio', 'studio'), ('apartment', 'apartment'), ('serviced apartment', 'serviced apartment'), ('chalet', 'chalet'), ('Industrial', 'Industrial'), ('duplex', 'duplex'), ('office', 'office'), ('retail', 'retail'), ('clinic', 'clinic'), ('villa', 'villa'), ('pent house', 'pent house')], max_length=100, verbose_name='Property Type'),
        ),
    ]
