# Generated by Django 3.2.5 on 2021-07-21 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GoldMark', '0008_alter_property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='Agent',
        ),
        migrations.AddField(
            model_name='property',
            name='Developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GoldMark.developer', verbose_name='Development group'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('town house', 'town house'), ('retail', 'retail'), ('restaurant', 'restaurant'), ('twin house', 'twin house'), ('Industrial', 'Industrial'), ('clinic', 'clinic'), ('studio', 'studio'), ('chalet', 'chalet'), ('pent house', 'pent house'), ('office', 'office'), ('serviced apartment', 'serviced apartment'), ('apartment', 'apartment'), ('duplex', 'duplex'), ('villa', 'villa')], max_length=100, verbose_name='Property Type'),
        ),
    ]
