# Generated by Django 3.2.5 on 2021-07-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoldMark', '0010_auto_20210721_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='features',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='property features'),
        ),
        migrations.AlterField(
            model_name='property',
            name='info',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='additional info as json string'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('studio', 'studio'), ('serviced apartment', 'serviced apartment'), ('pent house', 'pent house'), ('twin house', 'twin house'), ('Industrial', 'Industrial'), ('clinic', 'clinic'), ('duplex', 'duplex'), ('office', 'office'), ('town house', 'town house'), ('chalet', 'chalet'), ('retail', 'retail'), ('apartment', 'apartment'), ('restaurant', 'restaurant'), ('villa', 'villa')], max_length=100, verbose_name='Property Type'),
        ),
    ]
