# Generated by Django 3.2.5 on 2021-07-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoldMark', '0016_alter_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='website',
            field=models.URLField(default='google.com', verbose_name='Developer website'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.BooleanField(choices=[(False, 'For rent'), (True, 'For sale')], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('serviced apartment', 'serviced apartment'), ('retail', 'retail'), ('clinic', 'clinic'), ('villa', 'villa'), ('pent house', 'pent house'), ('duplex', 'duplex'), ('Industrial', 'Industrial'), ('chalet', 'chalet'), ('town house', 'town house'), ('studio', 'studio'), ('twin house', 'twin house'), ('apartment', 'apartment'), ('restaurant', 'restaurant'), ('office', 'office')], max_length=100, verbose_name='Property Type'),
        ),
    ]
