# Generated by Django 3.2.5 on 2021-07-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyMarket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='headquarters',
            field=models.CharField(max_length=100, verbose_name='Agency head quarters'),
        ),
    ]
