# Generated by Django 3.2.5 on 2021-07-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyMarket', '0003_agency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='propertyMarket/images/Agencies/profiles/', verbose_name='Agency logo'),
        ),
    ]
