# Generated by Django 3.2.5 on 2021-07-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyMarket', '0004_alter_agency_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Agency name'),
        ),
    ]
