# Generated by Django 3.2.5 on 2021-07-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyMarket', '0005_alter_agency_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agency',
            new_name='Developer',
        ),
        migrations.AddField(
            model_name='commercialproperty',
            name='type',
            field=models.CharField(choices=[('restaurant', 'restaurant'), ('clinic', 'clinic'), ('Industrial', 'Industrial'), ('retail', 'retail'), ('office', 'office')], default='office', max_length=100, verbose_name='Property Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residentialproperty',
            name='type',
            field=models.CharField(choices=[('town house', 'town house'), ('duplex', 'duplex'), ('studio', 'studio'), ('twin house', 'twin house'), ('pent house', 'pent house'), ('apartment', 'apartment'), ('serviced apartment', 'serviced apartment'), ('chalet', 'chalet'), ('villa', 'villa')], default='apartment', max_length=100, verbose_name='Property Type'),
            preserve_default=False,
        ),
    ]
