# Generated by Django 3.2.5 on 2021-07-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyMarket', '0009_auto_20210721_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='google latitude'),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='google longitude'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('pent house', 'pent house'), ('clinic', 'clinic'), ('apartment', 'apartment'), ('twin house', 'twin house'), ('office', 'office'), ('retail', 'retail'), ('villa', 'villa'), ('restaurant', 'restaurant'), ('chalet', 'chalet'), ('serviced apartment', 'serviced apartment'), ('town house', 'town house'), ('duplex', 'duplex'), ('Industrial', 'Industrial'), ('studio', 'studio')], max_length=100, verbose_name='Property Type'),
        ),
    ]
