# Generated by Django 3.2.5 on 2021-07-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyMarket', '0011_auto_20210721_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='propertyMarket/images/properties/residential/profiles', verbose_name='profile image'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('duplex', 'duplex'), ('apartment', 'apartment'), ('town house', 'town house'), ('villa', 'villa'), ('clinic', 'clinic'), ('pent house', 'pent house'), ('restaurant', 'restaurant'), ('chalet', 'chalet'), ('Industrial', 'Industrial'), ('retail', 'retail'), ('twin house', 'twin house'), ('office', 'office'), ('studio', 'studio'), ('serviced apartment', 'serviced apartment')], max_length=100, verbose_name='Property Type'),
        ),
    ]
