# Generated by Django 3.2.5 on 2021-07-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyMarket', '0013_auto_20210721_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.BooleanField(choices=[(True, 'For sale'), (False, 'For rent')], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('chalet', 'chalet'), ('town house', 'town house'), ('serviced apartment', 'serviced apartment'), ('retail', 'retail'), ('restaurant', 'restaurant'), ('clinic', 'clinic'), ('pent house', 'pent house'), ('Industrial', 'Industrial'), ('duplex', 'duplex'), ('office', 'office'), ('apartment', 'apartment'), ('twin house', 'twin house'), ('villa', 'villa'), ('studio', 'studio')], max_length=100, verbose_name='Property Type'),
        ),
    ]
