# Generated by Django 3.2.5 on 2021-07-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyMarket', '0015_auto_20210722_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('villa', 'villa'), ('restaurant', 'restaurant'), ('retail', 'retail'), ('office', 'office'), ('town house', 'town house'), ('studio', 'studio'), ('serviced apartment', 'serviced apartment'), ('clinic', 'clinic'), ('chalet', 'chalet'), ('duplex', 'duplex'), ('twin house', 'twin house'), ('pent house', 'pent house'), ('Industrial', 'Industrial'), ('apartment', 'apartment')], max_length=100, verbose_name='Property Type'),
        ),
    ]
